### ISSUE TITLE
SmartLoggerTestIntegrationML_I tests failed

### ISSUE THREAD

**Issue by Kero76** [SmartLoggerManagement/SmartLogger#2]
When I execute all test, the scenario `The scenario consist in test the normal behavior of SmartLogger application` present on SmartLoggerTestIntegrationML_I failed during process.
In fact, at the end of this test, I get this error : `org.scalatest.exceptions.TestFailedException: 1 did not equal 5`. So how can we fix it to execute the test with success ?

**Comment by KittyPwa** [comment]
Bug was found and cleaned in io/input/InputManagerTest. All tests pass as of today.
