### ISSUE TITLE
SmartLoggerTestIntegrationML_I_O.scala & SmartLoggerTestIntegrationML_I.scala failure

### ISSUE THREAD

**Issue by KittyPwa** [SmartLoggerManagement/SmartLogger#6]
Same error on both tests.
After extensive testing, this does not seem to come from testing code.
Possible reasons : Client?
(Replaced all conditions by tautologies, still get errors)

**Comment by TeeGreg** [comment]
Panne trouvée, cela viens des log, le format à été changer, donc le jeu de test utiliser n'est plus correct, il faut donc remplacer par de nouveau log au bon format.
